use SgdbT
-- Console 1: Reads all players twice with a delay
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION
SELECT * FROM BookType
WAITFOR DELAY '00:00:10'
SELECT * FROM BookType
COMMIT TRANSACTION

-- Solution: Use SERIALIZABLE to prevent phantom reads
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION
SELECT * FROM BookType
WAITFOR DELAY '00:00:10'
SELECT * FROM BookType
COMMIT TRANSACTION